version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12

  pre_build:
    commands:
      - echo Installing dependencies
      - npm install

  build:
    commands:
      - echo Running tests
      - echo Building and tagging Docker image
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 979490057625.dkr.ecr.us-east-1.amazonaws.com
      - docker build -t webapp .
      - docker tag webapp:latest 979490057625.dkr.ecr.us-east-1.amazonaws.com/webapp:latest
      
  post_build:
    commands:
      - echo Pushing to ECR
      - docker tag webapp:latest 979490057625.dkr.ecr.us-east-1.amazonaws.com/webapp:latest
      - printf '[{"name":"hamzaecs","imageUri":"979490057625.dkr.ecr.us-east-1.amazonaws.com/webapp:latest"}]' > imagedefinitions.json

  artifacts:
    files:
      - imagedefinitions.json
