version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12

  pre_build:
    commands:
      - echo Installing dependencies
      - npm install
      - apt-get install git

  build:
    commands:
      - echo Building and tagging Docker image
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 979490057625.dkr.ecr.us-east-1.amazonaws.com
      - docker build -t webapp .
      - docker tag webapp:${git rev-parse HEAD} 979490057625.dkr.ecr.us-east-1.amazonaws.com/webapp:${git rev-parse HEAD}
      
  post_build:
    commands:
      - echo Pushing to ECR
      - docker push 979490057625.dkr.ecr.us-east-1.amazonaws.com/webapp:${git rev-parse HEAD}
      - printf '[{"name":"hamzaecs","imageUri":"979490057625.dkr.ecr.us-east-1.amazonaws.com/webapp:${git rev-parse HEAD}"}]' > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
