version: 0.2
env:
  variables:
    COMMIT: git rev-parse HEAD
phases:
  install:
    runtime-versions:
      nodejs: 12

  pre_build:
    commands:
      - echo #{SourceVariables.CommitId}
      - echo Installing dependencies
      - npm install

  build:
    commands:
      - echo Building and tagging Docker image
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 979490057625.dkr.ecr.us-east-1.amazonaws.com
      - docker build -t webapp .
      - docker tag webapp:#{SourceVariables.CommitId} 979490057625.dkr.ecr.us-east-1.amazonaws.com/webapp:#{SourceVariables.CommitId}
      
  post_build:
    commands:
      - echo Pushing to ECR
      - docker push 979490057625.dkr.ecr.us-east-1.amazonaws.com/webapp:#{SourceVariables.CommitId}
      - printf '[{"name":"hamzaecs","imageUri":"979490057625.dkr.ecr.us-east-1.amazonaws.com/webapp:#{SourceVariables.CommitId} "}]' > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
