version: 0.2
env:
  variables:
    namespace: $CommitId
phases:
  install:
    runtime-versions:
      nodejs: 12

  pre_build:
    commands:
      - echo Installing dependencies
      - npm install

  build:
    commands:
      - echo $CommitId
      - echo Building and tagging Docker image
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 979490057625.dkr.ecr.us-east-1.amazonaws.com
      - docker pull 979490057625.dkr.ecr.us-east-1.amazonaws.com/hamzapp:latest
      - docker tag 979490057625.dkr.ecr.us-east-1.amazonaws.com/hamzapp:latest webapp:$CommitId
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 979490057625.dkr.ecr.us-east-1.amazonaws.com
      - docker tag webapp:$CommitId 979490057625.dkr.ecr.us-east-1.amazonaws.com/webapp:$CommitId
      - docker push 979490057625.dkr.ecr.us-east-1.amazonaws.com/webapp:$CommitId
      
  post_build:
    commands:
      - echo Pushing to ECR
      - docker push 979490057625.dkr.ecr.us-east-1.amazonaws.com/webapp:$CommitId
      - printf '[{"name":"hamzaecs","imageUri":"979490057625.dkr.ecr.us-east-1.amazonaws.com/webapp:$CommitId"}]' > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
