version: 0.2
run-as: root
phases:
  pre_build:
    commands:
      - echo Installing dependencies
      - npm install

  build:
    commands:
      - echo Building and tagging Docker image
      - echo Login
      - echo $CODEBUILD_RESOLVED_SOURCE_VERSION
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 979490057625.dkr.ecr.us-east-1.amazonaws.com
      - echo Building 
      - docker build -t webapp .
      - echo Tagging
      - docker tag 979490057625.dkr.ecr.us-east-1.amazonaws.com/webapp:latest webapp:$CODEBUILD_RESOLVED_SOURCE_VERSION
      
  post_build:
    commands:
      - echo Pushing to ECR
      - docker push 979490057625.dkr.ecr.us-east-1.amazonaws.com/webapp:$CODEBUILD_RESOLVED_SOURCE_VERSION
      - printf '[{"name":"hamzaecs","imageUri":"979490057625.dkr.ecr.us-east-1.amazonaws.com/webapp:$CODEBUILD_RESOLVED_SOURCE_VERSION"}]' > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
